import 'dart:convert';
import 'dart:io';
import 'package:dashlander/game/level_generator.dart';
import 'package:dashlander/game/models/level_data.dart';

extension LevelDataToJson on LevelData {
  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'name': name,
      'initialFuel': initialFuel,
      'terrainPoints': terrainPoints.map((p) => {'x': p.x, 'y': p.y}).toList(),
      'padIndices': padIndices,
      'padAngles': padAngles.map((k, v) => MapEntry(k.toString(), v)),
      'padAngleDeltas': padAngleDeltas.map((k, v) => MapEntry(k.toString(), v)),
      'startPosition': {'x': startPosition.x, 'y': startPosition.y},
      'initialVelocity': {'x': initialVelocity.x, 'y': initialVelocity.y},
      'radius': radius,
      'maxTerrainHeight': maxTerrainHeight,
      'padMultipliers': padMultipliers.map((k, v) => MapEntry(k.toString(), v)),
    };
  }
}

void main() {
  final seeds = [100, 200, 300, 400, 500, 600, 700, 800, 900, 1000];
  final file = File('test/test_levels_data.dart');
  
  StringBuffer sb = StringBuffer();
  sb.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  sb.writeln('// Generated by tool/generate_test_levels.dart');
  sb.writeln('const Map<int, Map<String, dynamic>> testLevelsData = {');

  for (var seed in seeds) {
    LevelData level = LevelGenerator.generate(seed: seed);
    String jsonString = jsonEncode(level.toJson());
    sb.writeln('  $seed: $jsonString,');
  }

  sb.writeln('};');
  file.writeAsStringSync(sb.toString());
  print('Generated 10 test levels at test/test_levels_data.dart');
}
