import 'dart:io';

void main() {
  try {
    final pubspecFile = File('pubspec.yaml');
    if (!pubspecFile.existsSync()) {
      stdout.writeln('pubspec.yaml not found');
      exit(1);
    }

    final lines = pubspecFile.readAsLinesSync();
    final versionLine = lines.firstWhere(
      (l) => l.trim().startsWith('version:'),
      orElse: () => '',
    );

    if (versionLine.isEmpty) {
      stdout.writeln('Version field not found in pubspec.yaml');
      exit(1);
    }

    final version = versionLine.split(':')[1].trim();

    final genDir = Directory('lib/gen');
    if (!genDir.existsSync()) {
      genDir.createSync(recursive: true);
    }

    final versionFile = File('lib/gen/version.dart');
    versionFile.writeAsStringSync(
      '''// Generated by update_version.dart. Do not edit.
const String appVersion = '$version';
''',
    );

    stdout.writeln('Successfully generated version: $version');
  } catch (e) {
    stdout.writeln('Error generating version: $e');
    exit(1);
  }
}
