{
  "format_version": 2,
  "sksl": {
    "entrypoint": "bloom_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 u_resolution;\nuniform shader u_texture;\nuniform half2 u_texture_size;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / u_resolution;\n    vec4 sum = vec4(0.0);\n    vec2 offset = vec2(1.0) / u_resolution;\n    float spread = 3.0;\n    for (float x = -2.0; x <= 2.0; x += 1.0)\n    {\n        for (float y = -2.0; y <= 2.0; y += 1.0)\n        {\n            vec4 sampleCol = u_texture.eval(u_texture_size * ( uv + ((vec2(x, y) * offset) * spread)));\n            float brightness = max(max(sampleCol.x, sampleCol.y), sampleCol.z);\n            if (brightness > 0.300000011920928955078125)\n            {\n                sum += ((sampleCol * (brightness - 0.300000011920928955078125)) * 1.39999997615814208984375);\n            }\n        }\n    }\n    vec4 bloom = sum / vec4(25.0);\n    vec4 col = u_texture.eval(u_texture_size * ( uv));\n    fragColor = col + (bloom * 1.5);\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "u_resolution",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 0,
        "columns": 1,
        "location": 1,
        "name": "u_texture",
        "rows": 1,
        "type": 12
      }
    ]
  }
}